<?xml version="1.0"?>
<robot name="hhbot_body" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Defining the colors -->
    <material name="Black">
        <color rgba="0.29 0.29 0.29 1"/>
    </material>

    <material name="White">
        <color rgba="0.96 0.96 0.98 1"/>
    </material>

    <material name="Red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- PROPERTY LIST -->
    <!-- All units in m-kg-s-radians unit system -->
    <xacro:property name="H_PI" value="3.1415926535897931" />

    <!-- Main body length, width, height and mass -->
    <xacro:property name="base_mass"        value="0.3" /> 
    <xacro:property name="base_link_length" value="0.25" />
    <xacro:property name="base_link_width"  value="0.14" />
    <xacro:property name="base_link_height" value="0.05"/>

    <!-- Wheel radius, height, centre and mass -->
    <xacro:property name="wheel_mass"   value="0.1" />
    <xacro:property name="wheel_radius" value="0.025" /> 
    <xacro:property name="wheel_length" value="0.02" />
    <xacro:property name="wheel_centre" value="0.005" />

    <!-- tail length, width, height, y and radian -->
    <xacro:property name="tail_width"  value="0.02" />
    <xacro:property name="tail_length" value="0.1" /> 
    <xacro:property name="tail_height" value="0.02" />
    <xacro:property name="tail_x"      value="-0.09" />
    <xacro:property name="tail_radian" value="-1.0472" />
    
    <!-- Macro for inertia matrix -->
    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                     iyy="${2*m*r*r/5}" iyz="0" 
                     izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                     iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                     izz="${m*r*r/2}" /> 
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertial_matrix" params="m w h d">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
                     iyy="${m*(w*w+d*d)/12}" iyz = "0"
                     izz="${m*(w*w+h*h)/12}" /> 
        </inertial>
    </xacro:macro>

    <!-- Macro for wheel -->
    <xacro:macro name="wheel" params="lr fb">
        <!-- lr: left, right , fb: front, back -->
        <link name="${lr}_${fb}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" /> 
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
                <material name="Black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
            </collision>
            <cylinder_inertial_matrix m="${wheel_mass}"
                                      r="${wheel_radius}" 
                                      h="${wheel_length}" />
        </link>

        <xacro:property name="sign_fb" value="-1.0" />
        <xacro:if value="${fb == 'front'}">
	        <xacro:property name="sign_fb" value="1.0" />
        </xacro:if>

        <xacro:property name="sign_lr" value="-1.0" />
        <xacro:if value="${lr == 'left'}">
	        <xacro:property name="sign_lr" value="1.0" />
        </xacro:if>

        <joint name="${lr}_${fb}_wheel_joint" type="continuous">
            <axis xyz="0 0 ${sign_lr}" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${lr}_${fb}_wheel_link" />
            <origin xyz="${sign_fb*(base_link_length/2-wheel_radius)}
                         ${sign_lr*base_link_width/2}
                         ${wheel_centre-wheel_radius}" 
                    rpy="${-H_PI/2} 0 0" /> 
        </joint>
    </xacro:macro>

    <!-- Macro for tail -->
    <xacro:macro name="tail">
        <link name="tail_link">  
            <visual>  
                <geometry>  
                    <box size="${tail_width} ${tail_length} ${tail_height}"/>  
                </geometry>  
                <material name="Red"/>  
            </visual>  
        </link>

        <joint name="tail_joint" type="fixed">  
            <parent link="base_link"/>  
            <child link="tail_link"/>  
            <origin rpy="0 ${tail_radian} 0" xyz="${tail_x} 0 ${base_link_height/2-0.002}"/>  
        </joint> 
    </xacro:macro>

    <!-- BASE-FOOTPRINT -->
    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
    <xacro:macro name="hhbot_body">
        <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0 " />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>

         <joint name="base_footprint_joint" type="fixed">
            <origin xyz="${base_link_length/2-wheel_radius} 
                         0
                         ${base_link_height/2+wheel_radius-wheel_centre}" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <!-- BASE-LINK -->
        <!--Actual body/chassis of the robot-->
        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${base_link_length} ${base_link_width} ${base_link_height}" />
                </geometry>
                <material name="White" />
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${base_link_length} ${base_link_width} ${base_link_height}" />
                </geometry>
            </collision>   
            
            <box_inertial_matrix  m="${base_mass}"
                                  w="${base_link_width}"
                                  h="${base_link_height}" 	
                                  d="${base_link_length}" />
        </link>

        <!-- Wheel Definitions -->
        <wheel lr="left"  fb="front" />
        <wheel lr="left"  fb="back" />
        <wheel lr="right" fb="front" />
        <wheel lr="right" fb="back" />
     
        <!-- Tail Definitions -->
        <tail/>

    </xacro:macro>
</robot>
