<?xml version="1.0"?>
<robot name="hhbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find hhbot_description)/urdf/hhbot_body.urdf.xacro" />
    <xacro:include filename="$(find hhbot_description)/urdf/camera.xacro" />
    
    <xacro:property name="camera_offset_x" value="0.06" />
    <xacro:property name="camera_offset_y" value="0" />
    <!-- Body of hhbot -->
    <hhbot_body/>

    <!-- Camera of hhbot -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_offset_x} ${camera_offset_y} ${base_link_height/2+0.015}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <xacro:usb_camera prefix="camera"/>

</robot>
