<?xml version="1.0"?>
<robot name="hhbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find hhbot_description)/urdf/hhbot_body.urdf.xacro" />
    <xacro:include filename="$(find hhbot_description)/urdf/kinect.xacro" />

    <xacro:property name="kinect_offset_x" value="0.05" />
    <xacro:property name="kinect_offset_y" value="0" />

    <!-- Body of hhbot -->
    <hhbot_body/>

    <!-- Kinect -->
    <joint name="kinect_frame_joint" type="fixed">
        <origin xyz="${kinect_offset_x} ${kinect_offset_y} ${base_link_height/2+0.02}"
                rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>
    <xacro:kinect_camera prefix="camera"/>

</robot>
