<?xml version="1.0"?>
<robot name="hhbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find hhbot_description)/urdf/hhbot_body.urdf.xacro" />
    <xacro:include filename="$(find hhbot_description)/urdf/rplidar.xacro" />
    
    <xacro:property name="rplidar_offset_x" value="0.05" />
    <xacro:property name="rplidar_offset_y" value="0" />

    <!-- Body of hhobot -->
    <hhbot_body/>

    <!-- laser of hhobot -->
    <joint name="rplidar_joint" type="fixed">
        <origin xyz="${rplidar_offset_x} ${rplidar_offset_y} ${base_link_height/2+0.02}"
                rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <xacro:rplidar prefix="laser"/>

</robot>
