obstacle_range: 2.5 
raytrace_range: 3.0 
footprint: [[0.07, 0.125], [0.07, -0.125], [-0.07, -0.125], [-0.07, 0.125]]
# robot_radius: 0.165
inflation_radius: 0.15
# footprint_inflation: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
